apiVersion: v2
name: caas-platform
description: Credit-as-a-Service Platform Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 22.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: prometheus
    version: 25.8.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.57.4
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

maintainers:
  - name: CaaS Platform Team
    email: devops@caas-platform.com

keywords:
  - credit
  - fintech
  - microservices
  - blockchain
  - lending

home: https://github.com/caas-platform/platform
sources:
  - https://github.com/caas-platform/platform
