apiVersion: v1
kind: ConfigMap
metadata:
  name: caas-platform-config
  namespace: caas-platform
  labels:
    app.kubernetes.io/name: caas-platform
    app.kubernetes.io/instance: caas-platform
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: caas-platform
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  API_URL: "http://caas-api:3002"
  WS_URL: "ws://caas-notifications:3010"
  PROVIDER_API_URL: "http://caas-credit-providers:3008"
  GRAPHQL_URL: "http://caas-graphql-gateway:3013"
  KAFKA_BROKER: "kafka:9092"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "caas_platform"
  PROMETHEUS_URL: "http://prometheus:9090"
  GRAFANA_URL: "http://grafana:3000"
  # Service URLs
  RISK_SERVICE_URL: "http://caas-risk-service:3015"
  COMPLIANCE_SERVICE_URL: "http://caas-compliance-service:3016"
  PROVIDER_SERVICE_URL: "http://caas-provider-service:3017"
  ANALYTICS_SERVICE_URL: "http://caas-analytics-service:3018"
  KAFKA_SERVICE_URL: "http://caas-kafka-service:3014"
  # Feature flags
  FEATURE_GRAPHQL_ENABLED: "true"
  FEATURE_KAFKA_ENABLED: "true"
  FEATURE_MONITORING_ENABLED: "true"
  FEATURE_AUTOSCALING_ENABLED: "true"
  # Security
  CORS_ORIGINS: "https://caas-platform.com,https://admin.caas-platform.com,https://provider.caas-platform.com"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  # Health check configuration
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "10"
  HEALTH_CHECK_RETRIES: "3"
  # Circuit breaker configuration
  CIRCUIT_BREAKER_ENABLED: "true"
  CIRCUIT_BREAKER_THRESHOLD: "5"
  CIRCUIT_BREAKER_TIMEOUT: "60000"
  CIRCUIT_BREAKER_RESET_TIMEOUT: "30000"
