apiVersion: v1
kind: Namespace
metadata:
  name: caas-platform
  labels:
    name: caas-platform
    app.kubernetes.io/name: caas-platform
    app.kubernetes.io/instance: caas-platform
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: caas-platform
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: caas-platform-quota
  namespace: caas-platform
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: caas-platform-limits
  namespace: caas-platform
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - max:
      cpu: 2000m
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Container
