apiVersion: v1
kind: Secret
metadata:
  name: caas-platform-secrets
  namespace: caas-platform
  labels:
    app.kubernetes.io/name: caas-platform
    app.kubernetes.io/instance: caas-platform
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: caas-platform
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  POSTGRES_PASSWORD: "" # base64 encoded
  REDIS_PASSWORD: "" # base64 encoded
  JWT_SECRET: "" # base64 encoded
  JWT_REFRESH_SECRET: "" # base64 encoded
  ENCRYPTION_KEY: "" # base64 encoded
  ADMIN_SECRET: "" # base64 encoded
  WEBHOOK_SECRET: "" # base64 encoded
  PROVIDER_WEBHOOK_SECRET: "" # base64 encoded
  NEXTAUTH_SECRET: "" # base64 encoded
  GRAFANA_PASSWORD: "" # base64 encoded
  # External service credentials
  SME_API_KEY: "" # base64 encoded
  CREDIT_BUREAU_API_KEY: "" # base64 encoded
  KYC_PROVIDER_KEY: "" # base64 encoded
  AML_PROVIDER_KEY: "" # base64 encoded
  PAYMENT_GATEWAY_SECRET: "" # base64 encoded
  PAYSTACK_SECRET_KEY: "" # base64 encoded
  STRIPE_SECRET_KEY: "" # base64 encoded
  # Blockchain credentials
  BLOCKCHAIN_PRIVATE_KEY: "" # base64 encoded
  BLOCKCHAIN_RPC_URL: "" # base64 encoded
  # External service URLs
  EMAIL_SERVICE_URL: "" # base64 encoded
  SMS_SERVICE_URL: "" # base64 encoded
  PUSH_SERVICE_URL: "" # base64 encoded
  OCR_SERVICE_URL: "" # base64 encoded
  ANTIVIRUS_SERVICE_URL: "" # base64 encoded
  ML_MODEL_URL: "" # base64 encoded
  # Monitoring
  SENTRY_DSN: "" # base64 encoded
  ALERT_WEBHOOK_URL: "" # base64 encoded
  # Storage
  AWS_ACCESS_KEY_ID: "" # base64 encoded
  AWS_SECRET_ACCESS_KEY: "" # base64 encoded
  AWS_REGION: "" # base64 encoded
  AWS_S3_BUCKET: "" # base64 encoded
